//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golemanite.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Golemanite.Content.Resources.Fish", typeof(Fish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuffaloDescr {
            get {
                return ResourceManager.GetString("BuffaloDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string BuffaloHeader {
            get {
                return ResourceManager.GetString("BuffaloHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string BuffaloName {
            get {
                return ResourceManager.GetString("BuffaloName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CommonBleakDescr {
            get {
                return ResourceManager.GetString("CommonBleakDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string CommonBleakHeader {
            get {
                return ResourceManager.GetString("CommonBleakHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string CommonBleakName {
            get {
                return ResourceManager.GetString("CommonBleakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CommonBreamDescr {
            get {
                return ResourceManager.GetString("CommonBreamDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string CommonBreamHeader {
            get {
                return ResourceManager.GetString("CommonBreamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string CommonBreamName {
            get {
                return ResourceManager.GetString("CommonBreamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CommonRoachDescr {
            get {
                return ResourceManager.GetString("CommonRoachDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string CommonRoachHeader {
            get {
                return ResourceManager.GetString("CommonRoachHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string CommonRoachName {
            get {
                return ResourceManager.GetString("CommonRoachName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EuropeanChubDescr {
            get {
                return ResourceManager.GetString("EuropeanChubDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string EuropeanChubHeader {
            get {
                return ResourceManager.GetString("EuropeanChubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string EuropeanChubName {
            get {
                return ResourceManager.GetString("EuropeanChubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GoldfishDescr {
            get {
                return ResourceManager.GetString("GoldfishDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string GoldfishHeader {
            get {
                return ResourceManager.GetString("GoldfishHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string GoldfishName {
            get {
                return ResourceManager.GetString("GoldfishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NorthPikeDescr {
            get {
                return ResourceManager.GetString("NorthPikeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string NorthPikeHeader {
            get {
                return ResourceManager.GetString("NorthPikeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string NorthPikeName {
            get {
                return ResourceManager.GetString("NorthPikeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PondPerchDescr {
            get {
                return ResourceManager.GetString("PondPerchDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string PondPerchHeader {
            get {
                return ResourceManager.GetString("PondPerchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string PondPerchName {
            get {
                return ResourceManager.GetString("PondPerchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RuddDescr {
            get {
                return ResourceManager.GetString("RuddDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string RuddHeader {
            get {
                return ResourceManager.GetString("RuddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string RuddName {
            get {
                return ResourceManager.GetString("RuddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RuffeDescr {
            get {
                return ResourceManager.GetString("RuffeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string RuffeHeader {
            get {
                return ResourceManager.GetString("RuffeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string RuffeName {
            get {
                return ResourceManager.GetString("RuffeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SilverCarpDescr {
            get {
                return ResourceManager.GetString("SilverCarpDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string SilverCarpHeader {
            get {
                return ResourceManager.GetString("SilverCarpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string SilverCarpName {
            get {
                return ResourceManager.GetString("SilverCarpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelsCatfishDescr {
            get {
                return ResourceManager.GetString("WelsCatfishDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string WelsCatfishHeader {
            get {
                return ResourceManager.GetString("WelsCatfishHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string WelsCatfishName {
            get {
                return ResourceManager.GetString("WelsCatfishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowPerchDescr {
            get {
                return ResourceManager.GetString("YellowPerchDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string YellowPerchHeader {
            get {
                return ResourceManager.GetString("YellowPerchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string YellowPerchName {
            get {
                return ResourceManager.GetString("YellowPerchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur imperdiet hendrerit. Aenean vulputate laoreet orci. Maecenas egestas urna neque, pharetra placerat nisl scelerisque quis. Praesent fringilla urna scelerisque tempus consequat. Vestibulum pellentesque, mi at mattis tincidunt, erat felis tristique quam, a pulvinar orci nibh eget nisl. Proin facilisis fringilla ex, vehicula sagittis metus dictum sit amet. Integer elementum eleifend turpis, sagittis eleifend nibh interdum vehicu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ZanderDescr {
            get {
                return ResourceManager.GetString("ZanderDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi..
        /// </summary>
        public static string ZanderHeader {
            get {
                return ResourceManager.GetString("ZanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Name.
        /// </summary>
        public static string ZanderName {
            get {
                return ResourceManager.GetString("ZanderName", resourceCulture);
            }
        }
    }
}
