//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golemanite.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Golemanite.Content.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.....
        /// </summary>
        public static string AddressCountry {
            get {
                return ResourceManager.GetString("AddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail: domain@mail.com.
        /// </summary>
        public static string AddressEmail {
            get {
                return ResourceManager.GetString("AddressEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region .....,.
        /// </summary>
        public static string AddressRegion {
            get {
                return ResourceManager.GetString("AddressRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel: +999 999 999 99.
        /// </summary>
        public static string AddressTelephone {
            get {
                return ResourceManager.GetString("AddressTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village/City,.
        /// </summary>
        public static string AddressVillage {
            get {
                return ResourceManager.GetString("AddressVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort.
        /// </summary>
        public static string Comfort {
            get {
                return ResourceManager.GetString("Comfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comfort intro.
        /// </summary>
        public static string ComfortIntro {
            get {
                return ResourceManager.GetString("ComfortIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointCapacity {
            get {
                return ResourceManager.GetString("ComfortPointCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointCourtyard {
            get {
                return ResourceManager.GetString("ComfortPointCourtyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointCourtyard_Bathroom {
            get {
                return ResourceManager.GetString("ComfortPointCourtyard_Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointCourtyard_Parking {
            get {
                return ResourceManager.GetString("ComfortPointCourtyard_Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointCourtyard_Pool {
            get {
                return ResourceManager.GetString("ComfortPointCourtyard_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointFirstFloor {
            get {
                return ResourceManager.GetString("ComfortPointFirstFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointFirstFloor_Bathroom {
            get {
                return ResourceManager.GetString("ComfortPointFirstFloor_Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointFirstFloor_SummerKitchen {
            get {
                return ResourceManager.GetString("ComfortPointFirstFloor_SummerKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointFirstFloor_Tavern {
            get {
                return ResourceManager.GetString("ComfortPointFirstFloor_Tavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointFirstFloor_WinterKitchen {
            get {
                return ResourceManager.GetString("ComfortPointFirstFloor_WinterKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointSecondFloor {
            get {
                return ResourceManager.GetString("ComfortPointSecondFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointSecondFloor_Rooms {
            get {
                return ResourceManager.GetString("ComfortPointSecondFloor_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointSecondFloor_Verand {
            get {
                return ResourceManager.GetString("ComfortPointSecondFloor_Verand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointTV {
            get {
                return ResourceManager.GetString("ComfortPointTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comfort description.
        /// </summary>
        public static string ComfortPointWiFi {
            get {
                return ResourceManager.GetString("ComfortPointWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts meta.
        /// </summary>
        public static string ContactsMetaDescription {
            get {
                return ResourceManager.GetString("ContactsMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Title.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET IN TOUCH.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filled in information is invalid.
        /// </summary>
        public static string ErrEmailInvalidRequestData {
            get {
                return ResourceManager.GetString("ErrEmailInvalidRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email could not be sent: {0}.
        /// </summary>
        public static string ErrEmailSendFormat {
            get {
                return ResourceManager.GetString("ErrEmailSendFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND US.
        /// </summary>
        public static string FindUs {
            get {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing.
        /// </summary>
        public static string Fishing {
            get {
                return ResourceManager.GetString("Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiam blandit mattis volutpat. Ut id quam laoreet, porta lectus a, sagittis est. Aenean tincidunt magna turpis, at sollicitudin ex sollicitudin ut. Vestibulum sed dui dignissim, ullamcorper dui hendrerit, lacinia augue. Sed ligula purus, commodo vitae nunc eget, tincidunt tincidunt diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam in lacinia est. Fusce auctor congue metus sit amet rhoncus. Donec ullamcorper sollicitudin augue sed semper..
        /// </summary>
        public static string FishingDescr {
            get {
                return ResourceManager.GetString("FishingDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GalleryCat {
            get {
                return ResourceManager.GetString("GalleryCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GalleryFirstFloor {
            get {
                return ResourceManager.GetString("GalleryFirstFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GalleryFirstFloorSummerKitchen {
            get {
                return ResourceManager.GetString("GalleryFirstFloorSummerKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GalleryFirstFloorTavern {
            get {
                return ResourceManager.GetString("GalleryFirstFloorTavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GalleryFirstFloorWinterKitchen {
            get {
                return ResourceManager.GetString("GalleryFirstFloorWinterKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GalleryInnerCourtyard {
            get {
                return ResourceManager.GetString("GalleryInnerCourtyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gallery meta.
        /// </summary>
        public static string GalleryMetaDescription {
            get {
                return ResourceManager.GetString("GalleryMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GallerySecondFloor {
            get {
                return ResourceManager.GetString("GallerySecondFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GallerySecondFloorBathroom {
            get {
                return ResourceManager.GetString("GallerySecondFloorBathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GallerySecondFloorRoom {
            get {
                return ResourceManager.GetString("GallerySecondFloorRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GallerySecondFloorUdaq {
            get {
                return ResourceManager.GetString("GallerySecondFloorUdaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string GallerySecondFloorVerand {
            get {
                return ResourceManager.GetString("GallerySecondFloorVerand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Title.
        /// </summary>
        public static string GalleryTitle {
            get {
                return ResourceManager.GetString("GalleryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Directions.
        /// </summary>
        public static string GetDirections {
            get {
                return ResourceManager.GetString("GetDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.Kolev.
        /// </summary>
        public static string GKolev {
            get {
                return ResourceManager.GetString("GKolev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///           Duis cursus ipsum non leo molestie placerat. Donec fringilla malesuada diam, a tincidunt sem sollicitudin a. Cras hendrerit enim at semper lobortis. Mauris mattis turpis eget lectus elementum, pretium lacinia nisi auctor. Proin lacinia enim sit amet venenatis ultricies. Nunc sit amet lectus eu leo consectetur porta et quis dui. Nulla ullamcorper ipsum et sapien iaculis, ac vulputate lacus scelerisque. Mauris quis eros id arcu molestie tincidunt et pellentesque nibh. Praesent tempus, lacus eu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HistoryDescr {
            get {
                return ResourceManager.GetString("HistoryDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting.
        /// </summary>
        public static string Hunting {
            get {
                return ResourceManager.GetString("Hunting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting &amp; Fishing.
        /// </summary>
        public static string HuntingAndFishing {
            get {
                return ResourceManager.GetString("HuntingAndFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiam blandit mattis volutpat. Ut id quam laoreet, porta lectus a, sagittis est. Aenean tincidunt magna turpis, at sollicitudin ex sollicitudin ut. Vestibulum sed dui dignissim, ullamcorper dui hendrerit, lacinia augue. Sed ligula purus, commodo vitae nunc eget, tincidunt tincidunt diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam in lacinia est. Fusce auctor congue metus sit amet rhoncus. Donec ullamcorper sollicitudin augue sed semper..
        /// </summary>
        public static string HuntingDescr {
            get {
                return ResourceManager.GetString("HuntingDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hunting meta.
        /// </summary>
        public static string HuntingMetaDescription {
            get {
                return ResourceManager.GetString("HuntingMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting and Fishing Title.
        /// </summary>
        public static string HuntingTitle {
            get {
                return ResourceManager.GetString("HuntingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your intro meta.
        /// </summary>
        public static string IntroMetaDescription {
            get {
                return ResourceManager.GetString("IntroMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string IntroTitle {
            get {
                return ResourceManager.GetString("IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string KilifarevoMonastery {
            get {
                return ResourceManager.GetString("KilifarevoMonastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia consequat. Sed quis congue leo, nec interdum arcu. Proin eu pellentesque mauris. Curabitur in pharetra nibh. Praesent enim eros, pellentesque vitae nibh nec, consequat tristique leo. Vestibulum id sapien leo. Nam vitae diam consequat, aliquam lacus a, tincidunt urna. Morbi hendrerit mollis neque. Nam id bibendum lacus. Integer eu laoreet urna, et convallis nisi.
        ///        &lt;/p&gt;
        ///&lt;p&gt;
        ///Etiam blandit mattis vo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LocationDescr {
            get {
                return ResourceManager.GetString("LocationDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationHead {
            get {
                return ResourceManager.GetString("LocationHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            Etiam interdum, dui ac finibus placerat, erat est condimentum massa, sit amet tempor ligula quam at urna. Mauris eleifend rutrum efficitur. Phasellus tincidunt lacinia purus, id pellentesque erat rutrum id. Morbi laoreet, sem at pulvinar dapibus, mauris lorem aliquet odio, id aliquam metus dui vel massa. Integer ipsum odio, cursus sed lobortis in, auctor aliquet arcu. In hac habitasse platea dictumst. Cras quis erat sit amet est pulvinar viverra. Phasellus mattis maximus nulla consectetur i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LocationInfastructure {
            get {
                return ResourceManager.GetString("LocationInfastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location meta.
        /// </summary>
        public static string LocationMetaDescription {
            get {
                return ResourceManager.GetString("LocationMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Title.
        /// </summary>
        public static string LocationTitle {
            get {
                return ResourceManager.GetString("LocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golemanite.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string PlaceholderMessage {
            get {
                return ResourceManager.GetString("PlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUESTS HOUSE.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since 1111.
        /// </summary>
        public static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The House.
        /// </summary>
        public static string TheHouse {
            get {
                return ResourceManager.GetString("TheHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your house meta.
        /// </summary>
        public static string TheHouseMetaDescription {
            get {
                return ResourceManager.GetString("TheHouseMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort, Why us Title.
        /// </summary>
        public static string TheHouseTitle {
            get {
                return ResourceManager.GetString("TheHouseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image descr.
        /// </summary>
        public static string TrakianTreasure {
            get {
                return ResourceManager.GetString("TrakianTreasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Bird&apos;s Eye.
        /// </summary>
        public static string ViewBirdsEye {
            get {
                return ResourceManager.GetString("ViewBirdsEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Larger Map.
        /// </summary>
        public static string ViewLargeMap {
            get {
                return ResourceManager.GetString("ViewLargeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Offer.
        /// </summary>
        public static string WeOffer {
            get {
                return ResourceManager.GetString("WeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Us.
        /// </summary>
        public static string WhyUs {
            get {
                return ResourceManager.GetString("WhyUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            Etiam interdum, dui ac finibus placerat, erat est condimentum massa, sit amet tempor ligula quam at urna. Mauris eleifend rutrum efficitur. Phasellus tincidunt lacinia purus, id pellentesque erat rutrum id. Morbi laoreet, sem at pulvinar dapibus, mauris lorem aliquet odio, id aliquam metus dui vel massa. Integer ipsum odio, cursus sed lobortis in, auctor aliquet arcu. In hac habitasse platea dictumst. Cras quis erat sit amet est pulvinar viverra. Phasellus mattis maximus nulla consectetur i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhyUsDescr {
            get {
                return ResourceManager.GetString("WhyUsDescr", resourceCulture);
            }
        }
    }
}
